config/routes.rb
Rails.application.routes.draw do

  resources :computers do
    member do
      get :overwrite, as: 'overwrite'
      patch :inplace, as: 'inplace'
    end
    collection do
      post :download_csv
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/seed', to: 'application#seed'

  get '/search', to: 'computers#search'
  post '/search', to: 'computers#search'

  get '/holdouts', to: 'users#holdouts'

  get '/sysinfo', to: 'downloads#sysinfo'

  get '/search_results', to: 'computers#search_results', as: 'search_results'
end

app/models/computer.rb
class Computer < ApplicationRecord
  belongs_to :computer, optional: true
  alias_attribute :parent, :computer

  belongs_to :user
  alias_attribute :owner, :user

  validates :serial, presence: true, allow_blank: false
  validates :ram, :processor, :space, numericality: true
  validates :wired_mac, :wireless_mac, mac_address: true, allow_blank: true

  enum status: [ :in_use, :available, :junk ]
  enum manufacturer: [ :"Apple", :"Dell", :"HP", :"Lenovo", :"Microsoft", :"Other" ]

  def title
    "#{name} | S/N: #{serial} #{" | P/N: #{product}" if !product.nil?}"
  end

  def date
    "#{updated_at.month}/#{updated_at.day}/#{updated_at.year}"
  end

  def possessive_name
    "#{owner.name}'s #{"#{manufacturer} " unless model.include? manufacturer}#{model} (#{status.humanize})"
  end

  def specs
    "RAM: #{ram} GB | Storage: #{space} GB | Processor: #{processor} GHz"
  end

  def macs
    "#{"Wired MAC: #{wired_mac} | " unless wired_mac.empty?}Wireless MAC: #{wireless_mac}"
  end

end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  require 'csv'
  before_action :set_computer, only: [:show, :edit, :update, :overwrite, :inplace, :destroy]
  before_action :gather_active
  before_action :require_admin, only: [:search, :search_results, :edit, :update, :overwrite, :inplace]

  # GET /computers
  # GET /computers.json
  def index
    computers = current_user.is_admin ? Computer.all : Computer.where(user: current_user)
    @computers = computers.where(history: false).sort_by(&:possessive_name)
  end

  def download_csv
    @computers = params[:computers].map { |x| Computer.find(x) }
    respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"#{params[:filename]}_#{DateTime.now.strftime("%Y-%m-%d_%H-%M-%S")}.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def search
    gather_owners
    index
  end

  def gather_owners
    @owners = Computer.all.map(&:owner).uniq.sort_by { |u| u.name  }
  end

  def search_results
    @computers = !params[:user][:id].empty? ? User.find(params[:user][:id]).computers : Computer.all

    @computers = @computers.where(history: false)

    @computers = @computers.to_a

    @computers = @computers.select { |c| c.manufacturer == params[:manufacturer][:manufacturer]} if !params[:manufacturer][:manufacturer].empty?

    @computers = @computers.select { |c| c.status == params[:status][:status] } if !params[:status][:status].empty?

    @computers = @computers.select { |c| c.serial == params[:serial].upcase } unless params[:serial].empty?

    @computers = @computers.select { |c| c.model.downcase.include? params[:model].downcase } unless params[:model].empty?

    @computers = @computers.select { |c| margin_of_error(c.ram, params[:ram].to_f, 1) } unless params[:ram].empty?

    @computers = @computers.select { |c| margin_of_error(c.space, params[:space].to_f, 50) } unless params[:space].empty?

    respond_to do |format|
      format.js
    end
  end

  def margin_of_error(a, b, margin)
    (a-b).abs <= margin
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
    if (@computer.history ||
        @computer.user != current_user) && !current_user.is_admin
      flash[:warning] = "Sorry, you can't see that computer!"
      redirect_to computers_path
    end
    gather_parents
  end

  def gather_parents
    @parents = []
    parent = @computer.parent
    while !parent.nil? do
      @parents << parent
      parent = parent.parent
    end
  end

  # GET /computers/new
  def new
    gather_active
    owner = (@active_users.include? current_user) ? current_user : User.where(name: current_user.name).first
    @computer = Computer.new(user: owner)
  end

  # GET /computers/1/edit
  def edit
    gather_active
  end

  def gather_active
    @active_users = User.where(active: true).order(:name)
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.where(serial: params['computer']['serial'],
                               manufacturer: params['computer']['manufacturer'])
                               .sort_by(&:updated_at).last
    if @computer.nil?
      @computer = Computer.new(fixed_params)

      respond_to do |format|
        if @computer.save
          format.html { redirect_to @computer }
          format.json { render :show, status: :created, location: @computer }
        else
          format.html { render :new }
          format.json { render json: @computer.errors, status: :unprocessable_entity }
        end
      end
    else
      @computer.history = false
      @computer.save!
      update
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    set_parent if @computer.history != true
    respond_to do |format|
      if @computer.update(fixed_params)
        format.html { redirect_to @computer }
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_parent
    parent = @computer.dup
    parent.history = true
    # parent.save!
    @computer.parent = parent
  end

  # GET /computers/overwrite/1
  # GET /computers/overwrite/1.json
  def overwrite
    gather_active
  end

  def inplace
    respond_to do |format|
      if @computer.update(fixed_params)
        format.html { redirect_to find_child(@computer) }
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  def find_child(current)
    child = Computer.where(computer: current).first
    child.nil? ? current : find_child(child)
  end

  def fixed_params
    my_params = computer_params
    my_params[:serial].upcase!
    my_params[:wired_mac] = format_mac(computer_params[:wired_mac])
    my_params[:wireless_mac] = format_mac(computer_params[:wireless_mac])
    if action_name != 'inplace'
      my_params[:comment_author] = @current_user.name
      my_params[:comments] = nil if (!@computer.nil? && @computer.comments == computer_params[:comments])
    end
    my_params[:comments] = nil if computer_params[:comments] == ""
    my_params
  end

  def format_mac(mac)
    mac.upcase.delete('-:').scan(/\w{2}/).join(':')
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html { redirect_to computers_url, notice: 'Computer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.all.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit(:name, :status, :history, :user_id, :manufacturer, :model, :serial, :wired_mac, :wireless_mac, :product, :space, :processor, :ram, :comments, :comment_author)
    end
end

app/helpers/computers_helper.rb
module ComputersHelper

  def list_init
    @list_counter = 0
  end

  def list
    @list_counter += 1
    "#{@list_counter}."
  end

  def sysinfo_link(text, bits)
    link_to text, sysinfo_path(bits: bits), download: ''
  end

end

app/views/computers/_form.html.erb
<%= form_for(computer) do |f| %>
  <% if computer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(computer.errors.count, "error") %> prohibited this computer from being saved:</h2>

      <ul>
      <% computer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :owner, "Your name:" %>
    &nbsp
    <%= f.text_field :owner %>
    &nbsp&nbsp
    <%= f.label :status, "Computer's current status:" %>
    &nbsp
    <%= f.select :status, options_for_select(@statuses.collect { |s| [s[0].humanize, s[0]] }, selected: @computer.status), {} %>
    &nbsp&nbsp
    <%= f.label :manufacturer, "Manufacturer:" %>
    &nbsp
    <%= f.select :manufacturer, options_for_select(@manufacturers.collect { |s| [s[0], s[0]] }, selected: @computer.manufacturer), {} %>

</br></br>

<h4> Open Command Prompt, type <code>msinfo32</code>, and press Enter. </h4>
<h4> A window will pop up with several pieces of information (you may have to scroll down). </h4>
  <div class "field">
    <%= f.label :name, "System Name:" %>
    &nbsp
    <%= f.text_field :name %>
    &nbsp&nbsp
    <%= f.label :model, "System Model:" %>
    &nbsp
    <%= f.text_field :model %>
    &nbsp&nbsp
    <%= f.label :product, "System SKU:" %>
    &nbsp
    <%= f.text_field :product %>
    &nbsp&nbsp
</br></br>
    <%= f.label :processor, "Processor (all we need is the number after the @ sign):" %>
    &nbsp
    <%= f.text_field :processor, :size=>"1" %> <strong>GHz</strong>
    &nbsp&nbsp
    <%= f.label :ram, "Installed Physical Memory (RAM):" %>
    &nbsp
    <%= f.text_field :ram, :size=>"1" %> <strong>GB</strong>
  </div>

</br>

<h4> Click the + next to "Components", then click on the + next to "Storage", then click on "Drives." </h4>

  <div class="field">
    <%= f.label :space, "Size (under drive C):" %>
    &nbsp
    <%= f.text_field :space %> <strong>GB</strong>
  </div>

 </br>

<h4> Go back to Command Prompt and run <code>wmic bios get serialnumber</code> to get your computer's serial number. </h4>
  </div>

  <div class="field">
    <%= f.label :serial, "Serial number:" %>
    &nbsp
    <%= f.text_field :serial %>
  </div>

  </br>

<h4> Last Command Prompt thing, I promise! Run <code>ipconfig /all</code>, then follow the instructions below to find the information you need. </h4>

  <div class="field">
    <%= f.label :wireless_mac, "Under \"Wireless LAN adapter Wi-Fi\", the twelve-character string labeled \"Physical Address\":" %>
    &nbsp
    <%= f.text_field :wireless_mac %>
  </div>

  <div class="field">
      <%= f.label :wired_mac, "<i>If your computer has an Ethernet port</i>: Under \"Ethernet adapter Local Area Connection\", the twelve-character string labeled \"Physical Address\".</br><i> Or, if you use a USB -> Ethernet adapter</i>: Under \"Ethernet Adapter Ethernet\", the twelve-character string labeled \"Physical Address\".".html_safe %>
      <%= f.text_field :wired_mac %>
  </div>

  </br>

  <div class="field">
    <%= f.label :comments, "<h4>Any additional comments:</h4>".html_safe %>
    &nbsp
    <%= f.text_field :comments, :size => 140 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/computers/_form_decider.html.erb
<%= render partial: "#{@computer.Apple? ? 'mac' : 'pc'}_form", locals: {computer: @computer, url: url} %>

app/views/computers/_history_computer.html.erb
<h4> <%= "#{computer.name} | #{computer.date}" %> </h4>
<h5> <%= computer.possessive_name %> </h5>
<h5> <%= computer.specs %> </h5>
<% if computer.comments %>
<h5><%= "Comments: \"#{computer.comments}\" -#{computer.comment_author}" %></h5>
<% end %>
<h6><u><%= link_to 'Overwrite', overwrite_computer_path(computer) if current_user.is_admin %></u><h6>

app/views/computers/_mac_form.html.erb
<%= form_for(computer, url: url) do |f| %>
  <% if computer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(computer.errors.count, "error") %> prohibited this computer from being saved:</h2>

      <ul>
      <% computer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4><div class="field">
    <%= f.label :user, "Computer's owner:" %>
    &nbsp
    <%= f.collection_select :user_id, @active_users, :id, :name, selected: @computer.user.id, :include_blank => true %>
    &nbsp&nbsp
    <%= f.label :status, "Computer's current status:" %>
    &nbsp
    <%= f.select :status, options_for_select(Computer.statuses.collect { |s| [s[0].humanize, s[0]] }, selected: @computer.status), {} %>
    &nbsp&nbsp
</div></h4>

</br>

<% list_init %>

<h4> <%=list%> Click on the Apple logo in the upper right corner of the screen, and click on About This Mac.</h4>
<h4>A window will pop up with several pieces of information. </h4>
  <div class "field">
    <%= f.label :model, "Computer model (eg. \"MacBook Pro (13-inch, Mid 2012)\" ):" %>
    &nbsp
    <%= f.text_field :model, :size=>"40" %>
    &nbsp&nbsp
    <%= f.label :serial, "Serial number:" %>
    &nbsp
    <%= f.text_field :serial %>
</br>
    <%= f.label :processor, "Processor speed:" %>
    &nbsp
    <%= f.text_field :processor, :size=>"1" %> <strong>GHz</strong>
    &nbsp&nbsp
    <%= f.label :ram, "Memory:" %>
    &nbsp
    <%= f.text_field :ram, :size=>"1" %> <strong>GB</strong>
  </div>

<hr>
<h4> <%=list%> At the top of the About This Mac window, click on Storage.</h4>

  <div class="field">
      <%= f.label :space, "Total hard drive size (the number below the hard drive icon on the left):" %>
      &nbsp
      <%= f.text_field :space, :size=>"2" %> <strong>GB</strong> (1 TB = 1000 GB)
  </div>

<hr>

<h4> <%=list%> Click on the Apple logo again, click on System Preferences..., and then click on Sharing. </h4>

  <div class="field">
      <%= f.label :name, "Computer Name:" %>
      &nbsp
      <%= f.text_field :name %>
      &nbsp&nbsp
  </div>

  <hr>

<h4> <%=list%> Click on the < button in the upper left corner of the window, then click on Network.</h4>
<h4>Make sure you're connected to both wifi and a wired connection.</h4>
<h4>For both of the two connection types on the left sidebar that say "Connected", follow these steps: </h4>
<strong><ol>
  <li>Click on the connection type in the left sidebar of the window</li>
  <li>Click on Advanced... in the lower right corner</li>
  <li>Click on Hardware</li>
  <li>Enter the MAC address into the field on this page</li>
</ol></strong>

  <div class="field">
    <%= f.label :wireless_mac, "Wi-Fi MAC address:" %>
    &nbsp
    <%= f.text_field :wireless_mac %>
    &nbsp&nbsp
    <%= f.label :wired_mac, "Wired MAC address (either Ethernet or an adapter):" %>
    <%= f.text_field :wired_mac %>
  </div>

  <hr>

  <div class="field">
    <%= f.label :comments, "<h4>#{list} Any additional comments:</h4>".html_safe %>
    &nbsp
    <%= f.text_field :comments, :size => 140 %>
    <%= f.hidden_field :manufacturer, :value => :Apple %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/computers/_pc_form.html.erb
<%= form_for(computer, url: url) do |f| %>
  <% if computer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(computer.errors.count, "error") %> prohibited this computer from being saved:</h2>

      <ul>
      <% computer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4><div class="field">
    <%= f.label :owner, "Computer's owner:" %>
    &nbsp
    <%= f.collection_select :user_id, @active_users, :id, :name, selected: @computer.user.id %>
</br></br>
    <%= f.label :status, "Computer's current status:" %>
    &nbsp
    <%= f.select :status, options_for_select(Computer.statuses.collect { |s| [s[0].humanize, s[0]] }, selected: @computer.status), {} %>
</br></br>
    <%= f.label :manufacturer, "Computer's manufacturer:" %>
    &nbsp
    <%= f.select :manufacturer, Computer.manufacturers.keys.to_a.from(1) %>
</div></h4>

<hr>

<h4> Click <u><%= sysinfo_link('here', 64) %></u> to download a tool that will list lots of information about your computer. </h4>
<h5> (Not working? Click <u><%= sysinfo_link('here', 32) %></u> to try another version of the tool.) </h5>
<h4> Make sure you have <i>both a wireless and wired network connection</i>, then open the file and click Run.</h4>
<h4> Close the square window with the detailed information about your processor.</h4>
<h4> You should see a large rectangular window. Follow these instructions to get the information we need:</h4>
<h5> (You can right-click on the desired line and click on "Copy Result" – <i>not "Copy Line"</i> –  and then paste it into the appropriate field.) </h5>

<hr>

<h4> <%=list%> That window should display some general information about your computer.</h4>
  <div class "field">
    <%= f.label :name, "Computer Name:" %>
    &nbsp
    <%= f.text_field :name %>
</div>

<hr>

<h4> <%=list%> Click on the + next to Central Processor(s), then on the name of your computer's processor. </h4>

<div class "field">
    <%= f.label :processor, "The number after the @ sign in \"CPU Brand Name\":" %>
    &nbsp
    <%= f.text_field :processor, :size=>"1" %> <strong>GHz</strong>
</div>

<hr>

<h4> <%=list%> Click on the + next to Motherboard, then on the + next to SMBIOS DMI, then on System. </h4>

<div class "field">
    <%= f.label :model, "Product Name:" %>
    &nbsp
    <%= f.text_field :model %>
    &nbsp&nbsp
    <%= f.label :serial, "Product Serial Number:" %>
    &nbsp
    <%= f.text_field :serial %>
    &nbsp&nbsp
    <%= f.label :product, "SKU Number:" %>
    &nbsp
    <%= f.text_field :product %>
</div>

<hr>

<h4> <%=list%> Click on Memory. </h4>

<div class "field">
    <%= f.label :ram, "Total Memory Size:" %>
    &nbsp
    <%= f.text_field :ram, :size=>"1" %> <strong>GB</strong>
</div>

<hr>

<h4> <%=list%> Click on the + next to Drives, then on the + next to (S)ATA/ATAPI Drives, then on the name of your hard drive. </h4>

<div class="field">
    <%= f.label :space, "Drive Capacity (in GB):" %>
    &nbsp
    <%= f.text_field :space, :size=>"2" %> <strong>GB</strong> (1 TB = 1000 GB)
</div>

 <hr>

<h4> <%=list%> Finally, click on the + next to Network to see your computer's network hardware. </h4>
<h4> You should see two entries, one for your wireless connection and one for wired. </h4>
<h4> Click on each of them to get specific information about them. </h4>

  <div class="field">
    <%= f.label :wireless_mac, "Wireless MAC Address:" %>
    &nbsp
    <%= f.text_field :wireless_mac %>
    &nbsp&nbsp
    <%= f.label :wired_mac, "Wired MAC Address:"%>
    &nbsp
    <%= f.text_field :wired_mac %>
  </div>

  <hr>

  <h4> <%=list%> Any additional comments? Things like:</h4>

  <h5><ul><strong>
      <li>Network issues</li>
      <li>Unexpected shutdowns/reboots</li>
      <li>Performance issues</li>
      <li>Port issues</li>
      <li>Screen issues</li>
  </strong></ul></h5>

  <h5><strong>Please be as detailed as possible when describing these issues so we can troubleshoot and follow up with you.</strong></h5>


  <div class="field">
    <%= f.text_field :comments, :size => 140 %>
  </div>

  <hr>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/computers/_root_computer.html.erb
<h3><u> <%=link_to "#{computer.title}", computer unless action_name == 'show' %> </u></h3>
<h4> <%= computer.possessive_name %> </h4>
<h4> <%= computer.specs %> </h4>
<h4> <%= computer.macs %> </h4>
<% if computer.comments %>
<h4><%= "Comments: \"#{computer.comments}\" -#{computer.comment_author}" %></h4>
<% end %>

<h5><u><%= link_to 'Overwrite', overwrite_computer_path(computer) if current_user.is_admin %></u><h5>

app/views/computers/_separator.html.erb
<hr>

app/views/computers/download_csv.csv.erb
<%- headers = ['Owner', 'Manufacturer', 'Model', 'Status', 'Serial Number', 'Product Number', 'Processor Speed', 'RAM', 'Storage'] -%>
<%= CSV.generate_line(headers).html_safe %>
<%- @computers.each do |computer| -%>
<%= CSV.generate_line([computer.owner.name, computer.manufacturer, computer.model, computer.status.humanize, computer.serial, computer.product, "#{computer.processor} GHz", "#{computer.ram} GB", "#{computer.space} GB"]).html_safe -%>
<%- end -%>

app/views/computers/edit.html.erb
<h3>Editing <%= @computer.possessive_name %></h3>

<% list_init %>

<%= render 'form_decider', url: nil %>

<%= link_to 'Back', computers_path %>

app/views/computers/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= pluralize(@computers.count, 'computer') %></h1>

<%= render partial: 'root_computer', collection: @computers, as: :computer, spacer_template: 'separator' %>

app/views/computers/overwrite.html.erb
<h3>Overwriting <%= "#{@computer.possessive_name} | #{@computer.date}" %></h3>

<% list_init %>

<%= render 'form_decider', url: inplace_computer_path(@computer) %>

<%= link_to 'Back', computers_path %>

app/views/computers/search.html.erb
<%= render partial: 'search_form' %>

<div id = "search_results">

<%= render partial: 'search_results' %>

</div>

app/views/computers/search_results.js.erb
$("#search_results").html("<%=escape_javascript(render(:partial => 'search_results'))%>")

app/views/computers/show.html.erb
<p id="notice"><%= notice %></p>

<h2> <%= "#{@computer.title}" %>
<% if current_user.is_admin %>
 | <u><%= link_to 'Edit', edit_computer_path(@computer) %></u>
<% end %>
</h2>
<%= render partial: 'root_computer', locals: {computer: @computer} %>

<hr>

<% parent = @computer.parent %>

<%= render partial: 'history_computer', collection: @parents, as: :computer, spacer_template: 'separator' %>