config/routes.rb
Rails.application.routes.draw do

  resources :computers do
    member do
      get :overwrite, as: 'overwrite'
      patch :inplace, as: 'inplace'
    end
    collection do
      post :download_csv
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/seed', to: 'application#seed'

  get '/search', to: 'computers#search'
  post '/search', to: 'computers#search'

  get '/holdouts', to: 'users#holdouts'

  get '/sysinfo', to: 'downloads#sysinfo'

  get '/search_results', to: 'computers#search_results', as: 'search_results'
end

app/views/layouts/_admin_header.html.erb
<li><%= link_to "Sync users with O365", seed_path %></li>
<li><%= link_to "Holdouts", holdouts_path %></li>
<li><%= link_to "Search", search_path %></li>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
<div class="container">
  <div class="navbar-header">
    <strong> <%= link_to 'FSENet Equipment Inventory', root_path, class: 'navbar-brand' %> </strong>
  </div>
  <div id="navbar">
    <ul class="nav navbar-nav pull-right">
    <% if current_user %>
        <%= render partial: 'layouts/admin_header' if current_user.is_admin %>
        <li><%= link_to "Computers", computers_path %></li>
        <li><%= link_to 'New Computer', new_computer_path %></li>
        <li><%= link_to "Log Out #{current_user.name}...", logout_path, method: :delete %></li>
    <% else %>
        <li><%= link_to 'Log in with Office 365', '/auth/office365' %></li>
    <% end %>
    <ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FSENet Equipment Inventory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= sanitize(value) %>
      </div>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>